BEGIN;

CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL DEFAULT '',
    last_name VARCHAR(50) NOT NULL DEFAULT '',
    email VARCHAR(100) UNIQUE,
    password TEXT NOT NULL DEFAULT '',
    type INTEGER DEFAULT 0
);

COMMIT;